#cloud-config

hostname: node2
coreos:
  etcd:
    name: node2
    addr: 10.10.1.118:4001
    bind-addr: 0.0.0.0
    peer-addr: 10.10.1.118:7001
    peers: 10.10.1.117:7001,10.10.1.124:7001
    peer-heartbeat-interval: 250
    peer-election-timeout: 1000
  units:
    - name: cbr0.netdev
      command: start
      content: |
        [NetDev]
        Kind=bridge
        Name=cbr0
    - name: cbr0.network
      command: start
      content: |
        [Match]
        Name=cbr0

        [Network]
        Address=10.244.2.1/24

        [Route]
        Destination=10.0.0.0/8
        Gateway=0.0.0.0
    - name: cbr0-interface.network
      command: start
      content: |
        [Match]
        Name=ens3

        [Network]
        Bridge=cbr0
    - name: nat.service
      command: start
      content: |
        [Unit]
        Description=NAT non container traffic

        [Service]
        ExecStart=/usr/sbin/iptables -t nat -A POSTROUTING -o enp0s8 -j MASQUERADE ! -d 10.0.0.0/8
        RemainAfterExit=yes
        Type=oneshot
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: docker.service
      command: start
      content: |
        [Unit]
        After=network.target
        Description=Docker Application Container Engine
        Documentation=http://docs.docker.io

        [Service]
        ExecStartPre=/bin/mount --make-rprivate /
        ExecStart=/usr/bin/docker -d -s=btrfs -H fd:// -b cbr0 --iptables=false

        [Install]
        WantedBy=multi-user.target
    - name: download-kubernetes.service
      command: start
      content: |
        [Unit]
        After=network-online.target
        Before=kubelet.service
        Before=proxy.service
        Description=Download Kubernetes Binaries
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=network-online.target

        [Service]
        ExecStart=/usr/bin/wget -N -P /opt/bin http://storage.googleapis.com/kubernetes/kubelet
        ExecStart=/usr/bin/wget -N -P /opt/bin http://storage.googleapis.com/kubernetes/proxy
        ExecStart=/usr/bin/chmod +x /opt/bin/kubelet
        ExecStart=/usr/bin/chmod +x /opt/bin/proxy
        RemainAfterExit=yes
        Type=oneshot
    - name: kubelet.service
      command: start
      content: |
        [Unit]
        ConditionFileIsExecutable=/opt/bin/kubelet
        Description=Kubernetes Kubelet
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes

        [Service]
        ExecStart=/opt/bin/kubelet \
        --address=0.0.0.0 \
        --port=10250 \
        --hostname_override=10.10.1.118 \
        --etcd_servers=http://127.0.0.1:4001 \
        --logtostderr=true
        Restart=always
        RestartSec=2

        [Install]
        WantedBy=multi-user.target
    - name: proxy.service
      command: start
      content: |
        [Unit]
        ConditionFileIsExecutable=/opt/bin/proxy
        Description=Kubernetes Proxy
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes

        [Service]
        ExecStart=/opt/bin/proxy --etcd_servers=http://127.0.0.1:4001 --logtostderr=true
        Restart=always
        RestartSec=2

        [Install]
        WantedBy=multi-user.target
  update:
    group: alpha
    reboot-strategy: off
ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDalszi0c3PkPOctr4TKUGLYftYC+/M15ICKqzcmav+lMPblFn/6jFRyQrT5pDcS5/Zdw3vVoVskfHTXsHtRAI9PJbFVqqQs0vpXaZ4MkSzs49QY5K0+hq4BPUxVVqr1AURHD5D+8tshNFLDHu3h48QL0juhnew2QWpxpw73in21xI8Z44pC+1Wy563rxLK/N8ggZPyQlmV1AK6Hk2OBqXjvJTQVRZPWQpK48FvqvgtUzWiOhC7cliZRZLpa2/VJRyHa+roZ42+9LxG6VWI1xnChHiQvK5FGRBxnF8GkD3coBwHgXl/6QrGxgJmlHeqixX6RlHXGVrG0ghbpZSpXbHZ bastichelaar@MacBook-Pro-van-Bas-2.local
    - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAm80GBFOjGxDBhPvV/U7V22oBxM7eyF3YTJYJpL/Q6Vh6Q+m5G851tGOZIST4bDP1cS9HydSwPLIYbM+OfQL/IFYnR8Dm5IvxxesYy8s5FnV0+pd04xKo4vADDLvuE0e4yMOTpT0IhQ0xdPAAQD8ISemLXXoekAoZh0yITiHjtmhYtP7NHCKBXNBFNr/mG2+RABNeJDpkb7sRu4nN2eQ4MXqbbCnwSIitPQsjCcezb0MmFigfFWtfJCHAen/Ikf5UkXHuaLgkEWRhZULDSZAJAjLov5Zqppqn2sr6uIKAEC34BQ8BnBO0DvHlsj6NmuQjJZQSC2fBN1xBSbPHMfMqSw==
